apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: appcd
  labels:
    app.kubernetes.io/name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-app
    spec:
      containers:
        - image: nginx
          name: web-app
          command:
            - /bin/sh
            - -c
            - "echo 'welcome to my web app!' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
      dnsConfig:
        options:
          - name: ndots
            value: "2"

---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: appcd
  labels:
    app.kubernetes.io/name: web-app
spec:
  selector:
    app.kubernetes.io/name: web-app
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: appcd
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
    - hosts:
        - web.v3il.xyz
      secretName: web-ingress-tls
  rules:
    - host: web.v3il.xyz
      http:
        paths:
          - backend:
              service:
                name: web-app
                port:
                  number: 80
            path: /
            pathType: Prefix
