apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: appcd
  labels:
    app: nginx-app
  spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - image: nginx
          name: web-app
          command:
            - /bin/sh
            - -c
            - "echo 'Welcome to my web app!' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
